### ISSUE TITLE
All subtitles are muxed in anime

### ISSUE THREAD

**Issue by Flwk** [einstein95/crunchy-xml-decoder#49]
Hey

I have an little probleme

When i downlod an anime, the script muxe all the subtitle in amkv, but i want juste one subtitle

In the settings.ini, i have add Francais but he doesn't worked.

Thanks in advance

PS : Sorry for my english, but i'm french

**Comment by alzamer2** [comment]
hi
i was the one who update the script so it can mux all subtitle available
one of the advantages of MKV file is the ability to mux different audio and subtitle
so what is the reason that only one subtitle depend on the answer i will add option in the settings for that


PS: dont tell me it because you dont want to change the subtitle to France every time you want to watch episode

**Comment by ganon11000** [comment]
Most media players allow you to set a default language (I have on VLC and Kodi) which you may want to set which will automatically choose that language over all others.

Really easy on VLC:
https://i.imgur.com/E3ezc8B.png -> https://i.imgur.com/jmVUP4m.png -> https://i.imgur.com/NJH8r3C.png

**Comment by alzamer2** [comment]
i know 
i use "Haali Media Splitter"
![1](https://cloud.githubusercontent.com/assets/4492974/11019255/d8490a78-85f8-11e5-8b17-c26fed3264e4.jpg)
![2](https://cloud.githubusercontent.com/assets/4492974/11019256/d84eb338-85f8-11e5-9199-e23f58f01611.jpg)
![3](https://cloud.githubusercontent.com/assets/4492974/11019257/d85552f6-85f8-11e5-901f-57a2dc1e7195.jpg)

just add "fre," before "eng"
![8](https://cloud.githubusercontent.com/assets/4492974/11019266/54885314-85f9-11e5-9c2c-a2ded599d478.jpg)

**Comment by Flwk** [comment]
Yes, but in my TV, it's very diffcult to change the subtitles, and i know that i can change de priority, but i don't know why my tv does'nt look the priority :(

alzamer2, i don't understand, do you will add an option for it ?

**Comment by ganon11000** [comment]
What TV do you have / software do you use on your TV?

**Comment by alzamer2** [comment]
hmm if it tv it may be hard
from what i know about tv that you can put priority, but after you turn it off it will change back to default, that for normal tv i dont know about smart tv

ok i will add the option

**Comment by alzamer2** [comment]
ok i added the option
try it out and if every thing is ok close this issue

**Comment by webtax** [comment]
Thanks for adding 1 subtitle back,seems to be working here.

I have no problems with multiple subs on my pc, and actually like it since i can easily check another language for a different translation, but my TV doesnt handle subtitles at all, so i have to convert all stuff to mp4 with burned subs using handbrakeCLI.

I setup a batch to convert them so i don't have to configure every time, and it works quite well, except handbrakeCLI apparently doesn't have a way to choose the correct sub when there are multiple subtitles. Been fiddling last couple of days trying to make it work to no avail, so one sub is a lifesaver :D thanks

**Comment by alzamer2** [comment]
as there no new replay with the last week i will close this issue
